### ISSUE TITLE
Unifier should accept multiple maps of macros

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/gosecco#1]
Macros shouldn't have to be defined in every file, we should support being able to use macros defined in other files. 

How to handle including only some but not necessarily all files? Maybe we can signify which ones to consider using "include" or something similar.

**Comment by olabini** [comment]
Just allow for the or unifier or startpoint to take a list of extra files.

**Comment by olabini** [comment]
Including the list of constants!
