### ISSUE TITLE
BPF Accept Inclusion

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/gosecco#10]
I'm not entirely sure how to handle this. 

Should we hold our value to compare against in X, and then keep loading values into A and then compare it to X? Or is there a more efficient way for this?

**Comment by olabini** [comment]
Whatever works. We can always emulate a statement like this: in(x, 1, 2, 3) with x == 1 || x == 2 || x == 3 - but we should try to make it more efficient.

**Comment by chelseakomlo** [comment]
Yes, that was the first thing I could think of, but wasn't sure how to make it more efficient...

**Comment by olabini** [comment]
We can special case it and make it more efficient later.

**Comment by chelseakomlo** [comment]
Do we need support for mixed-type inclusion statements? 

Such as:
6 in [arg1, 5, arg3]
or 
arg1 in [arg3, 5, 6]

**Comment by olabini** [comment]
Well, to be fair - all of these have the same type (numeric) - but yes, we need to support any kind of expression inside of either the .Left or the .Rights

**Comment by olabini** [comment]
In practice I think it will be very uncommon, but still.
