### ISSUE TITLE
Compile Boolean Literals

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/gosecco#13]
We should also handle these in expressions like boolean and comparison expressions.

**Comment by olabini** [comment]
Actually I don't think we should support them. In our kind of language they don't really add anything and we will always be able to reduce them away. The compiler should really never hit an actual boolean literal.

**Comment by olabini** [comment]
Does that make sense or do you want some examples?

**Comment by chelseakomlo** [comment]
Yes, we talked about whether we would ever hit this case. I think this is a good plan.

**Comment by chelseakomlo** [comment]
I'm going to close this issue then.
