### ISSUE TITLE
We need a new and better parser

### ISSUE THREAD

**Issue by olabini** [twtiger/gosecco#16]

**Comment by olabini** [comment]
I just pushed a handwritten recursive-descent parser using Ragel for tokenization. It's fairly simple and clean to understand, and stops us having to rely on Golang semantics and all that weird rewriting.

**Comment by chelseakomlo** [comment]
Great. I think seccomp-policy-language.md can be updated with this- it currently describes how gosecco syntax is limited to what Go supports.

**Comment by chelseakomlo** [comment]
I'm just going to update this now.

**Comment by olabini** [comment]
Sure, go for it.
