### ISSUE TITLE
We need support explicit loading of upper and lower argument halves

### ISSUE THREAD

**Issue by olabini** [twtiger/gosecco#18]
I have a proposal for this ready, but it needs to be implemented. I'll do this after the new parser is merged.

**Comment by olabini** [comment]
This is supported in the parser and the AST now - the compiler still needs to do the right thing in general with all the argument stuff.

**Comment by chelseakomlo** [comment]
Ok, can we close this then?

**Comment by yakiradixon** [comment]
@olabini Could you point out where this is happening in the new parser? I'm missing it. :/

**Comment by olabini** [comment]
It's here: https://github.com/twtiger/gosecco/blob/master/parser/parser.go#L368
It's not obvious, but it's done in the place that sets the "Type" field of the Argument structure.

**Comment by yakiradixon** [comment]
Ah. Understood. Thanks.

**Comment by chelseakomlo** [comment]
@olabini I believe we need to adapt the parser to do similar things with constants, no? For #20

**Comment by olabini** [comment]
Nope.

**Comment by olabini** [comment]
The literal numbres will always be parsed as a 64bit number.

**Comment by chelseakomlo** [comment]
Right. Thanks :)

**Comment by chelseakomlo** [comment]
Ok. So we need to change our NumericLiteral value types to uint64?

**Comment by olabini** [comment]
Indeed.
