### ISSUE TITLE
Comparison of arguments and constants should compare both upper and lower halves

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/gosecco#20]
go-seccomp loads constants in 64 bit format. We should compare the upper 32 bits of a constant to the upper 32 bits of an argument, and the lower halves similarly.

**Comment by olabini** [comment]
And also the other comparison operations.
I don't exactly know how to deal with the arithmetic operations. What happens if you do 0xFFFFFFFF + 1?

**Comment by chelseakomlo** [comment]
Yes, good point.

**Comment by chelseakomlo** [comment]
Ugh. Preparing myself to change almost every test we have :(

**Comment by chelseakomlo** [comment]
This task includes adapting NumericLiterals to support loading similar to Arguments.
