### ISSUE TITLE
Implement go-seccomp API interface

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/gosecco#21]
- [x] CheckSupport
- [x] Prepare
- [x] Compile
- [x] Load
- [x] Install
- [x] CompileBlacklist
- [x] InstallBlackList

**Comment by olabini** [comment]
I've added skeletons for these, but not implementations.
We might want to add CompileBlacklist and InstallBlacklist as well, for compatibility?

**Comment by chelseakomlo** [comment]
Yes, we should add.

**Comment by chelseakomlo** [comment]
For CheckSupport, should we do just as go-seccomp does? 
https://github.com/subgraph/go-seccomp/blob/master/seccomp.go#L452

**Comment by chelseakomlo** [comment]
Actually @olabini, another question. 

Should we support Compile and CompileBlackList as before? Or should Compile be able to handle both?

**Comment by chelseakomlo** [comment]
We need to talk about a good testing strategy for this. (mocking syscalls, etc)

**Comment by olabini** [comment]
I think we should keep both Compile and CompileBlacklist and try to make the API backwards compatible that way. They should all just be thin shims around the Prepare call with appropriate configurations in the config struct.

**Comment by olabini** [comment]
As mentioned in person, I'm not super concerned with mocking the syscalls and this stuff, it's small enough.

**Comment by olabini** [comment]
- "enforce" argument
  - for blacklist:
    - ALLOW: enforce means "kill", otherwise "trace"
    - THEN-part: enforce means "kill", otherwise "trace"
      - the then part is executed on POSITIVE outcome. otherwise def is executed.
  - for whitelist:
    - changes how the RETURN statement works. if enforce is false, RETURN will do TRACE, otherwise ERRNO

**Comment by olabini** [comment]
Prepare is currently not calling the simplifier, but once that's done, we are done.
