### ISSUE TITLE
Blacklist kill if NR > X32_SYSCALL_BIT-1

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/gosecco#23]
In a blacklist, kill if NR > X32_SYSCALL_BIT-1

**Comment by chelseakomlo** [comment]
@olabini what is NR?

**Comment by chelseakomlo** [comment]
In a blacklist, kill if NR > X32_SYSCALL_BIT-1

**Comment by chelseakomlo** [comment]
@olabini how do we know if a policy is a whitelist or blacklist? We don't have that distinction for a policy right now, just default positive and negative actions.

**Comment by chelseakomlo** [comment]
See #24

**Comment by chelseakomlo** [comment]
I believe this could be related to #20- we only compare syscalls to current syscall (32 bits)

**Comment by olabini** [comment]
Hm. There is something more I think.

**Comment by olabini** [comment]
I think we should make this customizable what happens. Basically, we should have a parameter X32_ABI_action that triggers if the X32_SYSCALL_BIT is set.

**Comment by olabini** [comment]
That should give the same behavior, if you compile with "kill" as the x32_abi_action.

**Comment by olabini** [comment]
This is done now.
