### ISSUE TITLE
Default return actions

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/gosecco#24]
- [ ] Blacklist default should be retAllow()
- [ ] Whitelist default should be kill if enforce, otherwise trace

**Comment by chelseakomlo** [comment]
I think these can be assigned in the unifier.

**Comment by chelseakomlo** [comment]
It isn't clear to me how we are differentiating whitelists and blacklists once the policy has been parsed. I'm going to add that, but we can revert if there is an existing solution to this.

**Comment by olabini** [comment]
To be crystal clear here - the difference between whitelists and blacklists only becomes interesting once we are compiling the policy - it is mostly concerned with what the default actions are etc.
