### ISSUE TITLE
Specify an action to take if none of the syscalls in a policy are matched

### ISSUE THREAD

**Issue by yakiradixon** [twtiger/gosecco#32]
In addition to our positive action (rulePositive) and negative action (ruleNegative) for rules, we want to specify an action to take when none of the syscalls in a policy are matched (policyNegative)

**Comment by olabini** [comment]
This includes updating the documentation, and also make a third _special_ variable, like DEFAULT_POSITIVE and the others.

**Comment by olabini** [comment]
This is not done until it works for the full stack.

**Comment by olabini** [comment]
This is done.

**Comment by chelseakomlo** [comment]
Right. You mean because it wasn't fully implemented in the API?
