### ISSUE TITLE
Fix all TODOs

### ISSUE THREAD

**Issue by olabini** [twtiger/gosecco#35]
We have plenty of TODOs left in the code base - we should address all those.

**Comment by chelseakomlo** [comment]
A lot of these are around testing different parts of the API. Do you have any ideas on how to do this effectively? I was thinking to do something similar to go-seccomp-tester but if there is anything easier let me know. Not sure about writing tests for all of the API because of system calls.

**Comment by olabini** [comment]
We can generate a policy file on the fly, give it to Prepare, and make sure we get the expected output. Should be fairly simple.

**Comment by chelseakomlo** [comment]
One todo is to check that simplification errors come through. What kind of errors would we expect from the simplifier that the type checker wouldn't catch before?

**Comment by chelseakomlo** [comment]
Same question with the compiler- what errors would we expect here that wouldn't be caught by the type checker or parser.

**Comment by olabini** [comment]
Probably nothing - it might not be useful to test those.

**Comment by chelseakomlo** [comment]
Ok. The only TODO that remains is testing our output against the go-seccomp library
