### ISSUE TITLE
Include policy file in another and combine prior to compilation

### ISSUE THREAD

**Issue by dma** [twtiger/gosecco#37]
Is there a way to include the contents of a file in a policy?

For example, this file: https://github.com/twtiger/gosecco/blob/master/profiles/shared.seccomp

Could be shared between multiple application whitelists.

I could have sworn this capability existed in gosecco, but I can't find it. Did I dream this or something?

**Comment by chelseakomlo** [comment]
You definitely did not dream this!

@olabini can expand more on this, but applying variables/constants/macros from a separate file into a policy file is done here: 

https://github.com/twtiger/gosecco/blob/master/seccomp.go#L41

Which is used here: 

https://github.com/twtiger/gosecco/blob/master/seccomp.go#L67

**Comment by dma** [comment]
Ah yes, now I remember, it's in the configuration object where you specify 'includes' and not as a directive in the policy file itself. Sorry for the noise!

**Comment by chelseakomlo** [comment]
No worries. We can specify this better in the documentation as well.
