### ISSUE TITLE
Macros that include previously defined variables can't resolve them

### ISSUE THREAD

**Issue by dma** [twtiger/gosecco#38]
Policy like this:

FUTEX_WAKE=1
FUTEX_PRIVATE_FLAG=128
FUTEX_WAKE_PRIVATE=(FUTEX_WAKE | FUTEX_PRIVATE_FLAG)
futex: arg1 == FUTEX_WAKE_PRIVATE 

Causes failure:

Jul 11 23:34:40 subgraph oz-daemon[21718]: 2016/07/11 23:34:40 [hexchat] (stderr) E Seccomp filter compile failed: [futex] found unresolved variable: FUTEX_WAKE

**Comment by chelseakomlo** [comment]
Hey, thanks for finding this. 

The failure is when we define macros that are based on their previous definitions, no? Will take a look at this tonight.

**Comment by dma** [comment]
Hi! Sure, no worries, I can work around it for now. Basically, the user expected behavior is that one can create a variable using other previously defined variables. I expect this to be quite common and hope this capability is easy to add to gosecco.

Here's how to reproduce quickly, the tester you provide with gosecco is handy for that.

Step 1: Create a policy that looks like this:

user@subgraph:/tmp$ cat >policy.seccomp <<EOF
> FUTEX_WAKE=1
> FUTEX_PRIVATE_FLAG=128
> FUTEX_WAKE_PRIVATE=(FUTEX_WAKE | FUTEX_PRIVATE_FLAG)
> futex: arg1 == FUTEX_WAKE_PRIVATE 
> EOF

Step 2: Try to compile with the tester:

user@subgraph:/tmp$ go run tester.go white true policy.seccomp 
Had error when compiling: &checker.ruleError{syscallName:"futex", err:(*errors.errorString)(0xc820070b90)} - [futex] found unresolved variable: FUTEX_WAKE

The compilation failure also occurs with variables in allConstants:

This policy demonstrates that:

user@subgraph:/tmp$ cat policy2.seccomp 
FUTEX_WAKE_PRIVATE=(O_RDONLY | AF_INET)
futex: arg1 == FUTEX_WAKE_PRIVATE 

user@subgraph:/tmp$ go run tester.go white true policy2.seccomp 
Had error when compiling: &checker.ruleError{syscallName:"futex", err:(*errors.errorString)(0xc82000ecb0)} - [futex] found unresolved variable: O_RDONLY

**Comment by olabini** [comment]
Hey, this has been fixed now. Very stupid mistake on my part. Hopefully it should all be good now.
