### ISSUE TITLE
License

### ISSUE THREAD

**Issue by justincormack** [twtiger/gosecco#39]
Just wondering if there is any chance you will relicense this software  under a different license? I am interested in using it (and contributing support for non x86 architectures that I would need), but all our software ships under the Apache license, and AGPL is not an option that we can use. (Currently using libseccomp, which is LGPL licensed).

**Comment by olabini** [comment]
Hi,

I'm sorry, but in general we will not reclicense away from AGPL.

Cheers

**Comment by justincormack** [comment]
Ok, thanks.

**Comment by olabini** [comment]
Re-evaluated and we have decided that switching to LGPL might be good after all.

**Comment by olabini** [comment]
Has been fixed in the latest release.
