### ISSUE TITLE
Compare upper half of arguments against 0

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/gosecco#4]
- Values in BPF can only be 32 bit, but arguments are 64 bits long
- Currently, we are comparing the lower half of the argument against K, but we need to compare the upper half of the argument against 0

**Comment by chelseakomlo** [comment]
Actually. In thinking about this, this would only be valid if we only compare arguments to numerics. Would there ever be a case where we could compare two arguments directly to each other?

**Comment by olabini** [comment]
Potentially, yes.
