### ISSUE TITLE
Some additional/corrected features requested for oz integration

### ISSUE THREAD

**Issue by shw700** [twtiger/gosecco#40]
A few miscellaneous issues found while upgrading oz to use gosecco:

* Constants for madvise() [like MADV_DONTNEED] are not present
* SO_REUSEPORT constant definition is missing
* ioctl() request code #'s are not present (TCGETS, etc.)
* A rule compilation error message should be more verbose. For example, "Variable not defined" should probably include the name of the offending variable for debugging purposes.

Additionally, the mapping from syscall names in syscalls[] to numbers seems to be done in a more hard-coded and less portable way than the way allConstants[] fields are mapped to their host-specific values. This might not be the most robust way to set up this table.

Finally, are there any plans for reverse mappings of allConstants? For example now we have:
allConstants["SIGUSR2"] = int(syscall.SIGUSR2);
Support for something like this might be helpful: constName = allConstNos["SIG", 9];
For now, it might be a good idea to make the table allConstants in go_constants.go named "AllConstants" so it can be exported for use by dependents.

**Comment by dma** [comment]
I want to add one detail:

When arg1 was mistyped as grg1, the error did not list that typo as the problem. The variable name that caused the compilation failure is displayed in other cases, e.g. arg1 == UNKNOWN_VARIABLE.

**Comment by olabini** [comment]
Thanks for this! I'll take a look today or tomorrow and make these changes!

**Comment by olabini** [comment]
OK, so - @shw700 - looking at madvise(), we do have MADV_DOFORK, MADV_DONTFORK, MADV_DONTNEED, MADV_HUGEPAGE, MADV_HWPOISON, MADV_MERGEABLE, MADV_NOHUGEPAGE, MADV_NORMAL, MADV_RANDOM, MADV_REMOVE, MADV_SEQUENTIAL, MADV_UNMERGEABLE and MADV_WILLNEED defined, so I'm not sure what your problem is with that.

**Comment by olabini** [comment]
I'm adding some more constants, such as TCGETS etc - but we might still be missing some.
When it comes to SO_REUSEPORT it's not there because we use the things that are exported by the syscall package in Golang - and SO_REUSEPORT is not there

The reason why the syscall numbers are defined in the way they are is because the golang syscall listing is missing quite a lot of the important syscall - we felt it better to have completeness than portability in that case.

**Comment by olabini** [comment]
When it comes to mapping numbers to constants, I'm not sure how much value a number to constant mapping would give you, since the constant values are in no way unique.

**Comment by olabini** [comment]
OK, I've pushed some fixes for the missing things - and also exposed the internal structures.

**Comment by shw700** [comment]
Hi Ola,

Thanks for the fast response. I'm really not sure at all how I missed out on the madvise() constants. I must have only searched for this once, with an undetected typo. 

As far as the reverse mappings go, we can make a reasonable prediction as to what the desired constant value is if we search within a string prefix.

For example, mapping the family parameter of a call to socket() we can reverse the number to a constant by comparing the value against any string in the map that begins with "AF_" ... There might be some hiccups with this... for example, with ioctl() some of the constants begin with "TC" or "TCI" or even "TIOC" ... then there is the matter of masked flags that need to be deconstructed into bitmasks. 

dma and I can discuss more whether this reverse mapping might be more appropriate to implement ourselves.

**Comment by olabini** [comment]
Sure. We can definitely very easily put in a reverse mapping that returns _all_ constant names that map to that number, and then the consumer can do the filtering.

**Comment by olabini** [comment]
OK, I've pushed some code to make this happen. Hope it's enough for your purposes!

**Comment by shw700** [comment]
Thanks!
