### ISSUE TITLE
Reverse mappings of allConstants

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/gosecco#44]

**Comment by dma** [comment]
What we did in our local gosecco repos is:

Capitalize allConstants so that it is exported, and apply that change throughout gosecco
Import github.com/twtiger/gosecco/constants in our own code to use it

That would work for us if it is agreeable to you.

**Comment by dma** [comment]
er, I just realized.. I'm talking about something slightly different here. We would also like the constants exported by gosecco as just something generally useful. That is a closely related, but perhaps distinct issue.

**Comment by chelseakomlo** [comment]
Ok, gotcha. Yes, we can definitely make that change as well!

**Comment by dma** [comment]
Just hold off on this: @shw700 and I are discussing the possibility of moving the constants / syscall name mapping to its own library.

**Comment by chelseakomlo** [comment]
Ok, fair enough. Let us know how we can help with this.

**Comment by olabini** [comment]
I've exposed the constants field now.
