### ISSUE TITLE
Better error messages for typos with known types

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/gosecco#45]
Specifically, things like 'grg1' instead of 'arg1' should raise an issue about a typo in the argument, rather than UNKNOWN_VARIABLE

**Comment by olabini** [comment]
How would we even do this?

**Comment by chelseakomlo** [comment]
I guess we could do fuzzy matching for args, if it would be worth it. I don't see how we could do anything else.

**Comment by olabini** [comment]
So I'm still confused why you opened this issue? What did you mean?

**Comment by chelseakomlo** [comment]
This issue is referred to in #40

**Comment by olabini** [comment]
Yes, it is. But my point is that when we create individual issues for tasks to be done, it would be great if we could have a higher standard than just copying it into a separate issue.

**Comment by chelseakomlo** [comment]
So, the issue is, for arguments, have a more specific error message (as the set of names for arguments is constrained) rather than having our generic "variable undefined" error. 

I can look at the feasibility for this.

**Comment by olabini** [comment]
Hm I guess I still don't understand. Arguments can exist at any place a scalar value can exist, so we can't really know that someone wants to have an argument there. We can try doing that, but that would lead to more confusing error messages for other types of variables in some cases.

**Comment by chelseakomlo** [comment]
Yes, agreed.

**Comment by olabini** [comment]
Since we can't really do anything about this, I'll close this issue now.
