### ISSUE TITLE
Feature request - compiling policy stored in memory object

### ISSUE THREAD

**Issue by dma** [twtiger/gosecco#49]
Currently we need to supply a path to a compilation unit  on the filesystem storing a gosecco policy. Would be very useful to us to skip this step and just pass a memory object that contains the policy text. This way we can ditch the bind-mount policy file inside the Oz sandbox and pass the policy via stdin before the wrapper executes the sandboxed application.

**Comment by olabini** [comment]
Sure, that should be easy to do.

**Comment by dma** [comment]
I thought so, thanks. It is something inherited from go-seccomp..
