### ISSUE TITLE
gosecco.Load() safe to use?

### ISSUE THREAD

**Issue by dma** [twtiger/gosecco#51]
There is one possible circumstance where we want to load a seccomp filter without setting NO_NEW_PRIVS at the same time because we are sure that it will be set very shortly thereafter and NNP gets in the way of something that needs to happen in between.

We could use the exported Load() function for this, but I noticed that gosecco.Load() doesn't lock the Golang thread as Install() does (before it calls Load()).. is this intended? Haven't tried calling Load() directly myself yet.

**Comment by olabini** [comment]
It's unclear to me whether Load by itself is safe to call - this needs closer investigation. I've added a new exported function, LockedLoad, that will lock the OS thread and run Load. We couldn't add this to Load ourselves, since LockOSThread is not reentrant in Golang...
