### ISSUE TITLE
Add other BPF_JMP comparison instructions

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/gosecco#6]
Currently, we only have jump if equal to. 

We should also add jump if greater/less than, greater than/equal to, etc.

**Comment by olabini** [comment]
I assume this is for the compiler.
We should also keep in mind that we can't actually do LT and LTE in the bytecode - we have to switch the L and R or negate the result of the comparison.

**Comment by chelseakomlo** [comment]
Yes, that is what is there. (Just switched the JT and JF for these cases).

**Comment by chelseakomlo** [comment]
Oh, I see what you mean. Wouldn't switching the JT and JF also achieve the same thing though?

**Comment by olabini** [comment]
Well, to emulate a LT, you would have to use a GTE and switch JT and JF - did is only true because we are using unsigned numbers with no overflow though - there are edge cases otherwise.

**Comment by chelseakomlo** [comment]
Great. That is what I did.
